/******************************************************************************
 * FIRESTARTER - A Processor Stress Test Utility
 * Copyright (C) 2020 TU Dresden, Center for Information Services and High
 * Performance Computing
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/\>.
 *
 * Contact: daniel.hackenberg@tu-dresden.de
 *****************************************************************************/

#pragma once

#include <firestarter/Environment/Environment.hpp>
#include <firestarter/Environment/AArch64/AArch64CPUTopology.hpp>

#include <firestarter/Environment/AArch64/Platform/AArch64DefaultConfig.hpp>

#include <asmjit/asmjit.h>

#include <functional>

#define REGISTER_AARCH64(NAME)                                                   \
  [](asmjit::CpuFeatures const &supportedFeatures, unsigned family,          \
     unsigned model, unsigned threads) -> platform::AArch64PlatformConfig * {      \
    return new platform::NAME(supportedFeatures, family, model, threads);      \
  }

namespace firestarter::environment::aarch64 {

class AArch64Environment final : public Environment {
public:
  AArch64Environment() : Environment(new AArch64CPUTopology()) {}

  ~AArch64Environment() {
    for (auto const &config : platformConfigs) {
      delete config;
    }
    for (auto const &config : fallbackPlatformConfigs) {
      delete config;
    }
  }

  AArch64CPUTopology const &topology() {
    return *reinterpret_cast<AArch64CPUTopology *>(this->_topology);
  }

  void evaluateFunctions() override;
  int selectFunction(unsigned functionId,
                     bool allowUnavailablePayload) override;
  int selectInstructionGroups(std::string groups) override;
  void printAvailableInstructionGroups() override;
  void setLineCount(unsigned lineCount) override;
  void printSelectedCodePathSummary() override;
  void printFunctionSummary() override;

private:
  // The available function IDs are generated by iterating through this list of
  // PlatformConfig. Add new PlatformConfig at the bottom to maintain stable
  // IDs.
  const std::list<std::function<platform::AArch64PlatformConfig *(
      asmjit::CpuFeatures const &, unsigned, unsigned, unsigned)>>
      platformConfigsCtor = {
          REGISTER_AARCH64(AArch64DefaultConfig)};

  std::list<platform::AArch64PlatformConfig *> platformConfigs;

  // List of fallback PlatformConfig. Add one for each ARM extension.
  const std::list<std::function<platform::AArch64PlatformConfig *(
      asmjit::CpuFeatures const &, unsigned, unsigned, unsigned)>>
      fallbackPlatformConfigsCtor = {
          REGISTER_AARCH64(AArch64DefaultConfig),   // Neon
      };

  std::list<platform::AArch64PlatformConfig *> fallbackPlatformConfigs;

#undef REGISTER_AARCH64
};

} // namespace firestarter::environment::aarch64
